// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: 'AIzaSyD4QE3PEaIBZImXpqqqVl2TNivdvQupR7k',
    appId: '1:346882274941:web:PLACEHOLDER',
    messagingSenderId: '346882274941',
    projectId: 'nabour-4b4e4',
    authDomain: 'nabour-4b4e4.firebaseapp.com',
    storageBucket: 'nabour-4b4e4.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: 'AIzaSyD4QE3PEaIBZImXpqqqVl2TNivdvQupR7k',
    appId: '1:346882274941:android:4b10a882274c050ed06314',
    messagingSenderId: '346882274941',
    projectId: 'nabour-4b4e4',
    storageBucket: 'nabour-4b4e4.firebasestorage.app',
  );
}