// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4QE3PEaIBZImXpqqaVl2TNiudvQupR7k',
    appId: '1:346882274941:web:nabour',
    messagingSenderId: '346882274941',
    projectId: 'nabour-4b4e4',
    authDomain: 'nabour-4b4e4.firebaseapp.com',
    storageBucket: 'nabour-4b4e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4QE3PEaIBZImXpqqaVl2TNiudvQupR7k',
    appId: '1:346882274941:android:4b10a882274c050ed06314',
    messagingSenderId: '346882274941',
    projectId: 'nabour-4b4e4',
    storageBucket: 'nabour-4b4e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK-ib5mvOWlq63HYj-bBQFL7pMPb81yfU',
    appId: '1:346882274941:ios:25ad7ec7bb2008d1d06314',
    messagingSenderId: '346882274941',
    projectId: 'nabour-4b4e4',
    storageBucket: 'nabour-4b4e4.firebasestorage.app',
    iosClientId: 'com.googleusercontent.apps.346882274941-ios',
    iosBundleId: 'com.florin.nabour',
  );
}
